name: Upgrade Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # monday at midnight
    - cron: '0 0 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade-wrapper:
    uses: github/data-pipelines/.github/workflows/gradle-upgrade.yaml@main
    secrets: inherit
    with:
      java-version: 17
      base-branch: master
